---
- name: Disable swap
  command: swapoff -a

- name: Hash out swap mounting in /etc/fstab
  lineinfile:
    path: /etc/fstab
    backup: true
    line: "#/swapfile none swap defaults 0 0"
    regexp: '^#?/swapfile none swap defaults 0 0'

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"

- name: Add source kubectl bash completion to .bashrc
  lineinfile:
    path: /root/.bashrc
    line: "{{ bashrc_lines }}"
    state: present
    insertafter: EOF
