---

- name: Download helm installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: 0775

- name: Execute installation script
  command:
    cmd: '/tmp/get_helm.sh'
  ignore_errors: true

- name: Install repos
  command:
    cmd: "/usr/local/bin/helm repo add {{ item.name }} {{ item.url }}"
  loop: "{{ helm_repos }}"


- name: Install haproxy-controller
  command:
    cmd: "/usr/local/bin/helm install haproxy-controller haproxytech/kubernetes-ingress"
